import { orderStatusMap, OrderStatus } from './regDetail';

export type IRegistrationCardItem = {
  sysCode: string;
  hosData?: string;
  deptName: string;
  ampm: string;
  orderId: string;
  patientId: string;
  numId: string;
  hosDeptId: string;
  idCard: string;
  fee: number;
  ampmName: string;
  hisResult: string;
  orderStatus: OrderStatus;
  idCasourcerd: string;
  upIdCard: string;
  schId: string;
  visitingArea: string;
  docName: string;
  categorName: string;
  appointmentTime: string;
  clinicalType: string;
  hosName: string;
  patientName: string;
  patientNameEncry: string;
  cardType: string;
  appointmentNumber: string;
  hosId: string;
  herenId: string;
  patientPhone: string;
  filing: string;
  hosOrderId: string;
  createTime: string;
  categor: string;
  hosDocId: string;
  appointmentDate: string;
  cardNumber: string;
  schQukCategor: string;
  _statusLabel: string;
  regWay?: string; // 挂号途径 小程序、自助机、诊间预约等
};
